zwitschereureka:
  image: "zwitscher-eureka:1.0.0"
  hostname: zwitschereureka
  ports:
    - "8761:8761"

zwitscherconfig:
  image: "zwitscher-config:1.0.0"
  hostname: zwitscherconfig
  links:
    - zwitschereureka
  environment:
    DOCKER_COMPOSE: true
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
  ports:
    - "8888:8888"

zwitscherservice:
  image: zwitscher-service:1.0.0
  hostname: zwitscherservice
  links:
    - zwitschereureka
    - zwitscherconfig
  environment:
    DOCKER_COMPOSE: true
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
  ports:
    - "8080:8080"

zwitscherboard:
  image: zwitscher-board:1.0.0
  hostname: zwitscherboard
  links:
    - zwitschereureka
    - zwitscherconfig
    - zwitscherservice
  environment:
    DOCKER_COMPOSE: true
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
  ports:
    - "8081:8081"

zwitscheredge:
  image: zwitscher-edge:1.0.0
  hostname: zwitscheredge
  links:
    - zwitschereureka
    - zwitscherconfig
    - zwitscherservice
    - zwitscherboard
  environment:
    DOCKER_COMPOSE: true
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
  ports:
    - "8765:8765"

zwitschermonitor:
  image: zwitscher-monitor:1.0.0
  hostname: zwitschermonitor
  links:
    - zwitschereureka
    - zwitscherconfig
    - zwitscherservice
    - zwitscherboard
    - zwitscheredge
  environment:
    DOCKER_COMPOSE: true
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
  ports:
    - "8989:8989"