zwitschereureka:
  image: "zwitscher-eureka:1.0.1"
  hostname: zwitschereureka
  environment:
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9761 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8761:8761"
    - "9761:9761"

zwitscherconfig:
  image: "zwitscher-config:1.0.1"
  hostname: zwitscherconfig
  links:
    - zwitschereureka
  environment:
    DOCKER_COMPOSE: 'true'
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9888 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8888:8888"
    - "9888:9888"

zwitscherservice:
  image: "zwitscher-service:1.0.1"
  hostname: zwitscherservice
  links:
    - zwitschereureka
    - zwitscherconfig
  environment:
    DOCKER_COMPOSE: 'true'
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9080 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8080:8080"
    - "9080:9080"

zwitscherboard:
  image: "zwitscher-board:1.0.1"
  hostname: zwitscherboard
  links:
    - zwitschereureka
    - zwitscherconfig
    - zwitscherservice
  environment:
    DOCKER_COMPOSE: 'true'
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9081 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8081:8081"
    - "9081:9081"

zwitscheredge:
  image: "zwitscher-edge:1.0.1"
  hostname: zwitscheredge
  links:
    - zwitschereureka
    - zwitscherconfig
    - zwitscherservice
    - zwitscherboard
  environment:
    DOCKER_COMPOSE: 'true'
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9765 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8765:8765"
    - "9765:9765"

zwitschermonitor:
  image: "zwitscher-monitor:1.0.1"
  hostname: zwitschermonitor
  links:
    - zwitschereureka
    - zwitscherconfig
    - zwitscherservice
    - zwitscherboard
    - zwitscheredge
  environment:
    DOCKER_COMPOSE: 'true'
    EUREKA_HOST: zwitschereureka
    EUREKA_PORT: 8761
    JAVA_OPTS: -Xmx128m -Dcom.sun.management.jmxremote.port=9989 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
  ports:
    - "8989:8989"
    - "9989:9989"
