zuul:
  ignoredPatterns: /**/admin/**
  routes:
    api:
      path: /api/**
      serviceId: zwitscher-service
      stripPrefix: true
    web:
      path: /**
      serviceId: zwitscher-board

endpoints:
  info:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false

logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO
    org.springframework.web: DEBUG
    de.qaware.cloud.nativ.zwitscher: DEBUG

management:
  context-path: /admin

eureka:
  instance:
    # register with IP addresses (required for deployment in Kubernetes?)
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health